# https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Tell me where workspace is
      working-directory: ${{ github.workspace }}
      run: ls -la

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build -- --if-present
        # npm test
      working-directory: ./solve-later-again
      env:
        CI: true
